In [1]:
import numpy as np
import tensorflow as tf

In [2]:
tf.__version__

'2.0.0'

Init some random vars

In [3]:
weights = tf.random.normal((1,5))

weights

<tf.Tensor: id=5, shape=(1, 5), dtype=float32, numpy=
array([[ 0.14742365,  0.60849476,  1.0818135 , -0.20019746, -1.3012512 ]],
      dtype=float32)>

In [4]:
weights.shape

TensorShape([1, 5])

In [6]:
features = tf.ones((1,5))

features

<tf.Tensor: id=11, shape=(1, 5), dtype=float32, numpy=array([[1., 1., 1., 1., 1.]], dtype=float32)>

In [7]:
bias = tf.random.normal((1,1))

In [8]:
weights, features, bias

(<tf.Tensor: id=5, shape=(1, 5), dtype=float32, numpy=
 array([[ 0.14742365,  0.60849476,  1.0818135 , -0.20019746, -1.3012512 ]],
       dtype=float32)>,
 <tf.Tensor: id=11, shape=(1, 5), dtype=float32, numpy=array([[1., 1., 1., 1., 1.]], dtype=float32)>,
 <tf.Tensor: id=17, shape=(1, 1), dtype=float32, numpy=array([[0.84970605]], dtype=float32)>)

Creating sigmoid activation function
$$
    sigmoid(x) = \frac{1}{1+e^{-x}}
$$

In [9]:
def sigmoid_activation(x):
    """ Sigmoid activation function
    
        Arguments
        ---------
        x: tf.Tensor. Must be one of the following types: bfloat16, half, float32, float64, complex64, complex128.
    """
    return 1/(1+tf.exp(-x))

In [11]:
sigmoid_activation(bias)

<tf.Tensor: id=24, shape=(1, 1), dtype=float32, numpy=array([[0.7005055]], dtype=float32)>

In [12]:
tf.reduce_sum(tf.multiply(weights, features))

<tf.Tensor: id=27, shape=(), dtype=float32, numpy=0.3362832>

In [15]:
tf.matmul(features, weights, transpose_b=True)

<tf.Tensor: id=31, shape=(1, 1), dtype=float32, numpy=array([[0.3362832]], dtype=float32)>

In [16]:
tf.matmul(features, weights, transpose_b=True) + bias

<tf.Tensor: id=33, shape=(1, 1), dtype=float32, numpy=array([[1.1859893]], dtype=float32)>

In [17]:
sigmoid_activation(tf.matmul(features, weights, transpose_b=True)+bias)

<tf.Tensor: id=41, shape=(1, 1), dtype=float32, numpy=array([[0.766023]], dtype=float32)>

### Creating a Multi-Layer NN

$$
\vec{h} = [h_1 \, h_2] = 
\begin{bmatrix}
x_1 \, x_2 \cdots \, x_n
\end{bmatrix}
\cdot 
\begin{bmatrix}
           w_{11} & w_{12} \\
           w_{21} &w_{22} \\
           \vdots &\vdots \\
           w_{n1} &w_{n2}
\end{bmatrix}
$$

The output for this small network is found by treating the hidden layer as inputs for the output unit. The network output is expressed simply as:

$$
y =  f_2 \! \left(\, f_1 \! \left(\vec{x} \, \mathbf{W_1}\right) \mathbf{W_2} \right)
$$

In [18]:
features.shape

TensorShape([1, 5])

In [19]:
n_input = features.shape[1]
n_hidden = 2
n_output = 1

In [20]:
W1 = tf.random.normal((n_input, n_hidden))
B1 = tf.ones((1,1))

In [21]:
W2 = tf.random.normal((n_hidden, n_output))
B2 = tf.ones((1,1))

In [22]:
W1, B1, W2, B2

(<tf.Tensor: id=47, shape=(5, 2), dtype=float32, numpy=
 array([[-0.88698125,  0.6598231 ],
        [-0.40367547,  0.8374479 ],
        [ 2.0129218 ,  0.8841053 ],
        [-2.4778452 , -0.62066215],
        [-0.32109094,  0.614773  ]], dtype=float32)>,
 <tf.Tensor: id=50, shape=(1, 1), dtype=float32, numpy=array([[1.]], dtype=float32)>,
 <tf.Tensor: id=56, shape=(2, 1), dtype=float32, numpy=
 array([[-0.44253692],
        [ 0.39022854]], dtype=float32)>,
 <tf.Tensor: id=59, shape=(1, 1), dtype=float32, numpy=array([[1.]], dtype=float32)>)

In [25]:
features.shape, W1.shape

(TensorShape([1, 5]), TensorShape([5, 2]))

In [26]:
out1 = tf.matmul(features, W1)
out1 = sigmoid_activation(out1 + B1)

In [27]:
out2 = tf.matmul(out1, W2)

In [28]:
output = sigmoid_activation(out2 + B2)

In [29]:
output

<tf.Tensor: id=76, shape=(1, 1), dtype=float32, numpy=array([[0.7798614]], dtype=float32)>

In [30]:
output.numpy()

array([[0.7798614]], dtype=float32)

In [31]:
anp = np.array([1,2,3,4,5])

In [32]:
anp

array([1, 2, 3, 4, 5])

In [33]:
tf.convert_to_tensor(anp)

<tf.Tensor: id=77, shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5])>